name: Build and Deploy Alert Rules

on:
  push:
    paths:
      - 'AnalyticsRules/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy Alert Rules
        run: |
          mkdir workspace
          cp AnalyticsRules/* workspace/

      - name: Validate JSON
        run: |
          for file in workspace/*.json; do
            jq empty "$file"
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RulesFile
          path: workspace
